version: '3'

services:

  halo:
    build:
      context: .
    restart: always
    volumes:
      - .:/usr/src/halo
      - ./test/init.yml:/usr/src/halo/init.d
    ports:
      - "8058:8058"
    healthcheck:
      test: curl --fail http://localhost:8055/api/ping || exit 1
